[project]
name = "llm-semantic-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=2.7.1",
    "pyyaml>=6.0.3",
    "tqdm>=4.67.1",
]
